language: node_js
os: osx
node_js:
- node
script:
- npm run build:all:mac
- ssh-keyscan -H ddns.swant.pw >> ~/.ssh/known_hosts
- chmod +x travis_sync.sh
- ./travis_sync.sh
deploy:
  provider: releases
  api_key:
    secure: "k4KmGscIj7KartFDeQfaRc1YPuEt82byJPjV2mXGLxHHR0BDmiHIWVYQtOc578dUCPJGDLqlWuAZyGo7Qgo8gIFBQ2JUHZaTQMf9AOkJZq/wMqLtMS0F1J2LNuLt/ufmDmogHPiMHd4zlwHBxRZtO9c4TamOayiGzg/nQrSr4jLfwSFYLuwSSEgioPGAZFHtACJbJm3RC0eZRqew23j84NqfVNG/vsRliKvwFo2wauQ9O4qLzd7cf0CIW8xQPiO7zHvU/Ad5wFal7EVbolnMBlVuXkNCUTu+bBYhcBFEDv5YPI+X2sh7Rjn+LMDE5epSvTdz+MJftlZpC0QxMevCeE0Dn/E2LX1rNte4VAEOY8lYgla5BOJXpRJ6GiFBhvXQXiUcn9cdQpTyuKwg3eg2A7QAJmZuL9/1hN+RKtXZ7S+yzLFsSPw14E7oDq7g7DaxB0U2gj8/XoZdM3TAoc5+zbXDyaOd+rXsJUq1OgmNuhqBLnsamVmcIX9stB/nwtn+TANGx9WutrOckVN83cmr00vRpGq1Pt8qDmgC+mhh4UamYn4+c+7xUpGiM0c+iaeffoYNvrfSdAYKOUj5OD1/6j5IntuNrcdf4ejzPD+IgD5tBKTRUmdwdBn0Wn1wbxwCcbtDyQiQOGo7d454vEqWVbJQMQ1Ev374lVEfGNYaCjg="
  file_glob: true
  file: dist/*/darwin/x64/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: svbeon/RopeScore
