# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pool:
  vmImage: 'vs2017-win2016'

strategy:
  matrix:
    au:
      command: 'build:au'
    se:
      command: 'build:se'
    intl:
      command: 'build:intl'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm run $(command) -a ia32
  displayName: 'npm run $(command) -a ia32'

- script: npm run $(command) -a x64
  displayName: 'npm run $(command) -a x64'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/dist
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: dist
