fragment CategoryResultsFragment on Category {
  competitionEventIds

  judgeAssignments {
    ...JudgeAssignmentFragment
    judge {
      ...JudgeBaseFragment
    }
  }

  participants {
    ...AthleteFragment
    ...TeamFragment
  }

  entries {
    ...EntryBaseFragment

    participant {
      ... on Athlete { id }
      ... on Team { id }
    }

    scoresheets {
      ...ScoresheetBaseFragment
      ...MarkScoresheetFragment
      ...TallyScoresheetFragment
    }
  }
}
