fragment ScoresheetBaseFragment on Scoresheet {
  id
  judge { id }

  rulesId
  judgeType
  competitionEventId

  createdAt
  updatedAt
  deletedAt

  options
}

fragment MarkScoresheetStatusFragment on MarkScoresheet {
  device {
    id
    name
  }

  completedAt
  submittedAt
  openedAt
}

fragment MarkScoresheetFragment on MarkScoresheet {
  ...MarkScoresheetStatusFragment

  marks
}

fragment TallyScoresheetFragment on TallyScoresheet {
  tally
}
