query CategoryGrid ($groupId: ID!, $categoryId: ID!) {
  group (groupId: $groupId) {
    id

    category (categoryId: $categoryId) {
      ...CategoryBaseFragment

      competitionEventIds

      participants {
        ...AthleteFragment
        ...TeamFragment
      }

      entries {
        ...EntryBaseFragment

        participant {
          ... on Athlete { id }
          ... on Team { id }
        }
      }
    }
  }
}
