query CurrentHeatScoresheets ($groupId: ID!, $heat: Int!) {
  group (groupId: $groupId) {
    id
    entriesByHeat (heat: $heat ) {
      ...EntryBaseFragment

      scoresheets {
        ...ScoresheetBaseFragment
        ...MarkScoresheetStatusFragment
      }
    }
  }
}
