query GroupInfo ($groupId: ID!) {
  group (groupId: $groupId) {
    ...GroupBaseFragment

    admins {
      id
      name
      username
    }
    viewers {
      id
      name
      username
    }
  }
}
