query Heats ($groupId: ID!) {
  group (groupId: $groupId) {
    ...GroupBaseFragment

    categories {
      ...CategoryBaseFragment

      judgeAssignments {
        ...JudgeAssignmentFragment
        judge {
          ...JudgeBaseFragment
        }
      }
    }

    entries {
      ...EntryBaseFragment

      category {
        id
      }

      participant {
        ...AthleteFragment
        ...TeamFragment
      }

      scoresheets {
        ...ScoresheetBaseFragment
        ...MarkScoresheetStatusFragment
      }
    }
  }
}
