on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build and Release RopeScore

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    name: Build and Release ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run electron:build -- -p always
        env:
          GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      # - name: Sentry Release
      #   if: startsWith(matrix.os, 'ubuntu')
      #   uses: getsentry/action-release@v1.0.0
      #   with:
      #     # Set the environment for this release. E.g. "production" or "staging".
      #     environment: production
      #     # Space-separated list of paths to JavaScript sourcemaps. Omit to skip uploading sourcemaps.
      #     sourcemaps: dist_electron/bundled/js/*.js.map
